channels:
  - bioconda
dependencies:
  - snakemake-minimal
  - python = 3.6
  - pyyaml

  - matplotlib
  - pysam
  - pandas

  - jupyter
  - notebook
  - qtconsole

  - trimmomatic
  - fastqc
  - bowtie2
  - samtools

